// Generated by gencpp from file cob_people_detection/captureImage.msg
// DO NOT EDIT!


#ifndef COB_PEOPLE_DETECTION_MESSAGE_CAPTUREIMAGE_H
#define COB_PEOPLE_DETECTION_MESSAGE_CAPTUREIMAGE_H

#include <ros/service_traits.h>


#include <cob_people_detection/captureImageRequest.h>
#include <cob_people_detection/captureImageResponse.h>


namespace cob_people_detection
{

struct captureImage
{

typedef captureImageRequest Request;
typedef captureImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct captureImage
} // namespace cob_people_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_people_detection::captureImage > {
  static const char* value()
  {
    return "86d49773917fcd20b952a821d3a9e019";
  }

  static const char* value(const ::cob_people_detection::captureImage&) { return value(); }
};

template<>
struct DataType< ::cob_people_detection::captureImage > {
  static const char* value()
  {
    return "cob_people_detection/captureImage";
  }

  static const char* value(const ::cob_people_detection::captureImage&) { return value(); }
};


// service_traits::MD5Sum< ::cob_people_detection::captureImageRequest> should match 
// service_traits::MD5Sum< ::cob_people_detection::captureImage > 
template<>
struct MD5Sum< ::cob_people_detection::captureImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_people_detection::captureImage >::value();
  }
  static const char* value(const ::cob_people_detection::captureImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_people_detection::captureImageRequest> should match 
// service_traits::DataType< ::cob_people_detection::captureImage > 
template<>
struct DataType< ::cob_people_detection::captureImageRequest>
{
  static const char* value()
  {
    return DataType< ::cob_people_detection::captureImage >::value();
  }
  static const char* value(const ::cob_people_detection::captureImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_people_detection::captureImageResponse> should match 
// service_traits::MD5Sum< ::cob_people_detection::captureImage > 
template<>
struct MD5Sum< ::cob_people_detection::captureImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_people_detection::captureImage >::value();
  }
  static const char* value(const ::cob_people_detection::captureImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_people_detection::captureImageResponse> should match 
// service_traits::DataType< ::cob_people_detection::captureImage > 
template<>
struct DataType< ::cob_people_detection::captureImageResponse>
{
  static const char* value()
  {
    return DataType< ::cob_people_detection::captureImage >::value();
  }
  static const char* value(const ::cob_people_detection::captureImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_PEOPLE_DETECTION_MESSAGE_CAPTUREIMAGE_H
