// Generated by gencpp from file cob_people_detection/finishRecording.msg
// DO NOT EDIT!


#ifndef COB_PEOPLE_DETECTION_MESSAGE_FINISHRECORDING_H
#define COB_PEOPLE_DETECTION_MESSAGE_FINISHRECORDING_H

#include <ros/service_traits.h>


#include <cob_people_detection/finishRecordingRequest.h>
#include <cob_people_detection/finishRecordingResponse.h>


namespace cob_people_detection
{

struct finishRecording
{

typedef finishRecordingRequest Request;
typedef finishRecordingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct finishRecording
} // namespace cob_people_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_people_detection::finishRecording > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::cob_people_detection::finishRecording&) { return value(); }
};

template<>
struct DataType< ::cob_people_detection::finishRecording > {
  static const char* value()
  {
    return "cob_people_detection/finishRecording";
  }

  static const char* value(const ::cob_people_detection::finishRecording&) { return value(); }
};


// service_traits::MD5Sum< ::cob_people_detection::finishRecordingRequest> should match 
// service_traits::MD5Sum< ::cob_people_detection::finishRecording > 
template<>
struct MD5Sum< ::cob_people_detection::finishRecordingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_people_detection::finishRecording >::value();
  }
  static const char* value(const ::cob_people_detection::finishRecordingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_people_detection::finishRecordingRequest> should match 
// service_traits::DataType< ::cob_people_detection::finishRecording > 
template<>
struct DataType< ::cob_people_detection::finishRecordingRequest>
{
  static const char* value()
  {
    return DataType< ::cob_people_detection::finishRecording >::value();
  }
  static const char* value(const ::cob_people_detection::finishRecordingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_people_detection::finishRecordingResponse> should match 
// service_traits::MD5Sum< ::cob_people_detection::finishRecording > 
template<>
struct MD5Sum< ::cob_people_detection::finishRecordingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_people_detection::finishRecording >::value();
  }
  static const char* value(const ::cob_people_detection::finishRecordingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_people_detection::finishRecordingResponse> should match 
// service_traits::DataType< ::cob_people_detection::finishRecording > 
template<>
struct DataType< ::cob_people_detection::finishRecordingResponse>
{
  static const char* value()
  {
    return DataType< ::cob_people_detection::finishRecording >::value();
  }
  static const char* value(const ::cob_people_detection::finishRecordingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_PEOPLE_DETECTION_MESSAGE_FINISHRECORDING_H
