// Generated by gencpp from file cob_people_detection/recognitionTrigger.msg
// DO NOT EDIT!


#ifndef COB_PEOPLE_DETECTION_MESSAGE_RECOGNITIONTRIGGER_H
#define COB_PEOPLE_DETECTION_MESSAGE_RECOGNITIONTRIGGER_H

#include <ros/service_traits.h>


#include <cob_people_detection/recognitionTriggerRequest.h>
#include <cob_people_detection/recognitionTriggerResponse.h>


namespace cob_people_detection
{

struct recognitionTrigger
{

typedef recognitionTriggerRequest Request;
typedef recognitionTriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct recognitionTrigger
} // namespace cob_people_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_people_detection::recognitionTrigger > {
  static const char* value()
  {
    return "0fb2bbc7af64ffad2d27794be36bc198";
  }

  static const char* value(const ::cob_people_detection::recognitionTrigger&) { return value(); }
};

template<>
struct DataType< ::cob_people_detection::recognitionTrigger > {
  static const char* value()
  {
    return "cob_people_detection/recognitionTrigger";
  }

  static const char* value(const ::cob_people_detection::recognitionTrigger&) { return value(); }
};


// service_traits::MD5Sum< ::cob_people_detection::recognitionTriggerRequest> should match 
// service_traits::MD5Sum< ::cob_people_detection::recognitionTrigger > 
template<>
struct MD5Sum< ::cob_people_detection::recognitionTriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_people_detection::recognitionTrigger >::value();
  }
  static const char* value(const ::cob_people_detection::recognitionTriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_people_detection::recognitionTriggerRequest> should match 
// service_traits::DataType< ::cob_people_detection::recognitionTrigger > 
template<>
struct DataType< ::cob_people_detection::recognitionTriggerRequest>
{
  static const char* value()
  {
    return DataType< ::cob_people_detection::recognitionTrigger >::value();
  }
  static const char* value(const ::cob_people_detection::recognitionTriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_people_detection::recognitionTriggerResponse> should match 
// service_traits::MD5Sum< ::cob_people_detection::recognitionTrigger > 
template<>
struct MD5Sum< ::cob_people_detection::recognitionTriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_people_detection::recognitionTrigger >::value();
  }
  static const char* value(const ::cob_people_detection::recognitionTriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_people_detection::recognitionTriggerResponse> should match 
// service_traits::DataType< ::cob_people_detection::recognitionTrigger > 
template<>
struct DataType< ::cob_people_detection::recognitionTriggerResponse>
{
  static const char* value()
  {
    return DataType< ::cob_people_detection::recognitionTrigger >::value();
  }
  static const char* value(const ::cob_people_detection::recognitionTriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_PEOPLE_DETECTION_MESSAGE_RECOGNITIONTRIGGER_H
