; Auto-generated. Do not edit!


(cl:in-package cob_people_detection-msg)


;//! \htmlinclude addDataFeedback.msg.html

(cl:defclass <addDataFeedback> (roslisp-msg-protocol:ros-message)
  ((images_captured
    :reader images_captured
    :initarg :images_captured
    :type cl:integer
    :initform 0))
)

(cl:defclass addDataFeedback (<addDataFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <addDataFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'addDataFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_people_detection-msg:<addDataFeedback> is deprecated: use cob_people_detection-msg:addDataFeedback instead.")))

(cl:ensure-generic-function 'images_captured-val :lambda-list '(m))
(cl:defmethod images_captured-val ((m <addDataFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_people_detection-msg:images_captured-val is deprecated.  Use cob_people_detection-msg:images_captured instead.")
  (images_captured m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <addDataFeedback>) ostream)
  "Serializes a message object of type '<addDataFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'images_captured)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <addDataFeedback>) istream)
  "Deserializes a message object of type '<addDataFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'images_captured) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<addDataFeedback>)))
  "Returns string type for a message object of type '<addDataFeedback>"
  "cob_people_detection/addDataFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'addDataFeedback)))
  "Returns string type for a message object of type 'addDataFeedback"
  "cob_people_detection/addDataFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<addDataFeedback>)))
  "Returns md5sum for a message object of type '<addDataFeedback>"
  "0bd9d2345b5b8d85a254a7569f431459")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'addDataFeedback)))
  "Returns md5sum for a message object of type 'addDataFeedback"
  "0bd9d2345b5b8d85a254a7569f431459")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<addDataFeedback>)))
  "Returns full string definition for message of type '<addDataFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback message~%int32 images_captured			# the number of images already captured~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'addDataFeedback)))
  "Returns full string definition for message of type 'addDataFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback message~%int32 images_captured			# the number of images already captured~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <addDataFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <addDataFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'addDataFeedback
    (cl:cons ':images_captured (images_captured msg))
))
