; Auto-generated. Do not edit!


(cl:in-package cob_people_detection-msg)


;//! \htmlinclude addDataResult.msg.html

(cl:defclass <addDataResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass addDataResult (<addDataResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <addDataResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'addDataResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_people_detection-msg:<addDataResult> is deprecated: use cob_people_detection-msg:addDataResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <addDataResult>) ostream)
  "Serializes a message object of type '<addDataResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <addDataResult>) istream)
  "Deserializes a message object of type '<addDataResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<addDataResult>)))
  "Returns string type for a message object of type '<addDataResult>"
  "cob_people_detection/addDataResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'addDataResult)))
  "Returns string type for a message object of type 'addDataResult"
  "cob_people_detection/addDataResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<addDataResult>)))
  "Returns md5sum for a message object of type '<addDataResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'addDataResult)))
  "Returns md5sum for a message object of type 'addDataResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<addDataResult>)))
  "Returns full string definition for message of type '<addDataResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'addDataResult)))
  "Returns full string definition for message of type 'addDataResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <addDataResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <addDataResult>))
  "Converts a ROS message object to a list"
  (cl:list 'addDataResult
))
