; Auto-generated. Do not edit!


(cl:in-package cob_people_detection-msg)


;//! \htmlinclude deleteDataFeedback.msg.html

(cl:defclass <deleteDataFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass deleteDataFeedback (<deleteDataFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <deleteDataFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'deleteDataFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_people_detection-msg:<deleteDataFeedback> is deprecated: use cob_people_detection-msg:deleteDataFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <deleteDataFeedback>) ostream)
  "Serializes a message object of type '<deleteDataFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <deleteDataFeedback>) istream)
  "Deserializes a message object of type '<deleteDataFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<deleteDataFeedback>)))
  "Returns string type for a message object of type '<deleteDataFeedback>"
  "cob_people_detection/deleteDataFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'deleteDataFeedback)))
  "Returns string type for a message object of type 'deleteDataFeedback"
  "cob_people_detection/deleteDataFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<deleteDataFeedback>)))
  "Returns md5sum for a message object of type '<deleteDataFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'deleteDataFeedback)))
  "Returns md5sum for a message object of type 'deleteDataFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<deleteDataFeedback>)))
  "Returns full string definition for message of type '<deleteDataFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'deleteDataFeedback)))
  "Returns full string definition for message of type 'deleteDataFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <deleteDataFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <deleteDataFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'deleteDataFeedback
))
