; Auto-generated. Do not edit!


(cl:in-package cob_people_detection-msg)


;//! \htmlinclude getDetectionsGoal.msg.html

(cl:defclass <getDetectionsGoal> (roslisp-msg-protocol:ros-message)
  ((maximum_message_age
    :reader maximum_message_age
    :initarg :maximum_message_age
    :type cl:float
    :initform 0.0)
   (timeout
    :reader timeout
    :initarg :timeout
    :type cl:float
    :initform 0.0))
)

(cl:defclass getDetectionsGoal (<getDetectionsGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <getDetectionsGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'getDetectionsGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_people_detection-msg:<getDetectionsGoal> is deprecated: use cob_people_detection-msg:getDetectionsGoal instead.")))

(cl:ensure-generic-function 'maximum_message_age-val :lambda-list '(m))
(cl:defmethod maximum_message_age-val ((m <getDetectionsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_people_detection-msg:maximum_message_age-val is deprecated.  Use cob_people_detection-msg:maximum_message_age instead.")
  (maximum_message_age m))

(cl:ensure-generic-function 'timeout-val :lambda-list '(m))
(cl:defmethod timeout-val ((m <getDetectionsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_people_detection-msg:timeout-val is deprecated.  Use cob_people_detection-msg:timeout instead.")
  (timeout m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <getDetectionsGoal>) ostream)
  "Serializes a message object of type '<getDetectionsGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'maximum_message_age))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'timeout))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <getDetectionsGoal>) istream)
  "Deserializes a message object of type '<getDetectionsGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'maximum_message_age) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'timeout) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<getDetectionsGoal>)))
  "Returns string type for a message object of type '<getDetectionsGoal>"
  "cob_people_detection/getDetectionsGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'getDetectionsGoal)))
  "Returns string type for a message object of type 'getDetectionsGoal"
  "cob_people_detection/getDetectionsGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<getDetectionsGoal>)))
  "Returns md5sum for a message object of type '<getDetectionsGoal>"
  "dd64e18e045dc05a5cb38c8f05510e32")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'getDetectionsGoal)))
  "Returns md5sum for a message object of type 'getDetectionsGoal"
  "dd64e18e045dc05a5cb38c8f05510e32")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<getDetectionsGoal>)))
  "Returns full string definition for message of type '<getDetectionsGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%float32 maximum_message_age		# maximal allowed age of response message (in s), 0 means we do not care~%float32 timeout				# maximal waiting time (in s) for receiving a detection, 0 is infinitely. If the detection pipeline was not running before, it will start upon receiving this message and collect messages for the full timeout period.~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'getDetectionsGoal)))
  "Returns full string definition for message of type 'getDetectionsGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%float32 maximum_message_age		# maximal allowed age of response message (in s), 0 means we do not care~%float32 timeout				# maximal waiting time (in s) for receiving a detection, 0 is infinitely. If the detection pipeline was not running before, it will start upon receiving this message and collect messages for the full timeout period.~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <getDetectionsGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <getDetectionsGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'getDetectionsGoal
    (cl:cons ':maximum_message_age (maximum_message_age msg))
    (cl:cons ':timeout (timeout msg))
))
