; Auto-generated. Do not edit!


(cl:in-package cob_people_detection-msg)


;//! \htmlinclude loadModelResult.msg.html

(cl:defclass <loadModelResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass loadModelResult (<loadModelResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <loadModelResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'loadModelResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_people_detection-msg:<loadModelResult> is deprecated: use cob_people_detection-msg:loadModelResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <loadModelResult>) ostream)
  "Serializes a message object of type '<loadModelResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <loadModelResult>) istream)
  "Deserializes a message object of type '<loadModelResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<loadModelResult>)))
  "Returns string type for a message object of type '<loadModelResult>"
  "cob_people_detection/loadModelResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'loadModelResult)))
  "Returns string type for a message object of type 'loadModelResult"
  "cob_people_detection/loadModelResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<loadModelResult>)))
  "Returns md5sum for a message object of type '<loadModelResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'loadModelResult)))
  "Returns md5sum for a message object of type 'loadModelResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<loadModelResult>)))
  "Returns full string definition for message of type '<loadModelResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'loadModelResult)))
  "Returns full string definition for message of type 'loadModelResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <loadModelResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <loadModelResult>))
  "Converts a ROS message object to a list"
  (cl:list 'loadModelResult
))
