; Auto-generated. Do not edit!


(cl:in-package cob_people_detection-msg)


;//! \htmlinclude loadModelFeedback.msg.html

(cl:defclass <loadModelFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass loadModelFeedback (<loadModelFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <loadModelFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'loadModelFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_people_detection-msg:<loadModelFeedback> is deprecated: use cob_people_detection-msg:loadModelFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <loadModelFeedback>) ostream)
  "Serializes a message object of type '<loadModelFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <loadModelFeedback>) istream)
  "Deserializes a message object of type '<loadModelFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<loadModelFeedback>)))
  "Returns string type for a message object of type '<loadModelFeedback>"
  "cob_people_detection/loadModelFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'loadModelFeedback)))
  "Returns string type for a message object of type 'loadModelFeedback"
  "cob_people_detection/loadModelFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<loadModelFeedback>)))
  "Returns md5sum for a message object of type '<loadModelFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'loadModelFeedback)))
  "Returns md5sum for a message object of type 'loadModelFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<loadModelFeedback>)))
  "Returns full string definition for message of type '<loadModelFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'loadModelFeedback)))
  "Returns full string definition for message of type 'loadModelFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <loadModelFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <loadModelFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'loadModelFeedback
))
