; Auto-generated. Do not edit!


(cl:in-package cob_people_detection-msg)


;//! \htmlinclude updateDataFeedback.msg.html

(cl:defclass <updateDataFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass updateDataFeedback (<updateDataFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <updateDataFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'updateDataFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_people_detection-msg:<updateDataFeedback> is deprecated: use cob_people_detection-msg:updateDataFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <updateDataFeedback>) ostream)
  "Serializes a message object of type '<updateDataFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <updateDataFeedback>) istream)
  "Deserializes a message object of type '<updateDataFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<updateDataFeedback>)))
  "Returns string type for a message object of type '<updateDataFeedback>"
  "cob_people_detection/updateDataFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'updateDataFeedback)))
  "Returns string type for a message object of type 'updateDataFeedback"
  "cob_people_detection/updateDataFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<updateDataFeedback>)))
  "Returns md5sum for a message object of type '<updateDataFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'updateDataFeedback)))
  "Returns md5sum for a message object of type 'updateDataFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<updateDataFeedback>)))
  "Returns full string definition for message of type '<updateDataFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'updateDataFeedback)))
  "Returns full string definition for message of type 'updateDataFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <updateDataFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <updateDataFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'updateDataFeedback
))
