; Auto-generated. Do not edit!


(cl:in-package cob_people_detection-msg)


;//! \htmlinclude updateDataResult.msg.html

(cl:defclass <updateDataResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass updateDataResult (<updateDataResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <updateDataResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'updateDataResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_people_detection-msg:<updateDataResult> is deprecated: use cob_people_detection-msg:updateDataResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <updateDataResult>) ostream)
  "Serializes a message object of type '<updateDataResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <updateDataResult>) istream)
  "Deserializes a message object of type '<updateDataResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<updateDataResult>)))
  "Returns string type for a message object of type '<updateDataResult>"
  "cob_people_detection/updateDataResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'updateDataResult)))
  "Returns string type for a message object of type 'updateDataResult"
  "cob_people_detection/updateDataResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<updateDataResult>)))
  "Returns md5sum for a message object of type '<updateDataResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'updateDataResult)))
  "Returns md5sum for a message object of type 'updateDataResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<updateDataResult>)))
  "Returns full string definition for message of type '<updateDataResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'updateDataResult)))
  "Returns full string definition for message of type 'updateDataResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <updateDataResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <updateDataResult>))
  "Converts a ROS message object to a list"
  (cl:list 'updateDataResult
))
