; Auto-generated. Do not edit!


(cl:in-package cob_people_detection-msg)


;//! \htmlinclude updateDataActionGoal.msg.html

(cl:defclass <updateDataActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type cob_people_detection-msg:updateDataGoal
    :initform (cl:make-instance 'cob_people_detection-msg:updateDataGoal)))
)

(cl:defclass updateDataActionGoal (<updateDataActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <updateDataActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'updateDataActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_people_detection-msg:<updateDataActionGoal> is deprecated: use cob_people_detection-msg:updateDataActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <updateDataActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_people_detection-msg:header-val is deprecated.  Use cob_people_detection-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <updateDataActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_people_detection-msg:goal_id-val is deprecated.  Use cob_people_detection-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <updateDataActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_people_detection-msg:goal-val is deprecated.  Use cob_people_detection-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <updateDataActionGoal>) ostream)
  "Serializes a message object of type '<updateDataActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <updateDataActionGoal>) istream)
  "Deserializes a message object of type '<updateDataActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<updateDataActionGoal>)))
  "Returns string type for a message object of type '<updateDataActionGoal>"
  "cob_people_detection/updateDataActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'updateDataActionGoal)))
  "Returns string type for a message object of type 'updateDataActionGoal"
  "cob_people_detection/updateDataActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<updateDataActionGoal>)))
  "Returns md5sum for a message object of type '<updateDataActionGoal>"
  "0b0388e146474b842a2e77050e12d484")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'updateDataActionGoal)))
  "Returns md5sum for a message object of type 'updateDataActionGoal"
  "0b0388e146474b842a2e77050e12d484")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<updateDataActionGoal>)))
  "Returns full string definition for message of type '<updateDataActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%updateDataGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: cob_people_detection/updateDataGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Updates data in the training database~%#~%# goal message~%int32 update_mode			# update the label with new_label either for 1=one image given the update_index, 2=all entries labeled with old_label~%int32 update_index			# the database entry with this index number shall be updated with a new label~%string old_label			# all database entries carrying this label are to be updated with new_label~%string new_label			# the new label that is supposed to replace the old one~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'updateDataActionGoal)))
  "Returns full string definition for message of type 'updateDataActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%updateDataGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: cob_people_detection/updateDataGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Updates data in the training database~%#~%# goal message~%int32 update_mode			# update the label with new_label either for 1=one image given the update_index, 2=all entries labeled with old_label~%int32 update_index			# the database entry with this index number shall be updated with a new label~%string old_label			# all database entries carrying this label are to be updated with new_label~%string new_label			# the new label that is supposed to replace the old one~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <updateDataActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <updateDataActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'updateDataActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
